#!/usr/bin/env python3

import sys

from w3af.core.controllers.dependency_check.dependency_check import dependency_check

if __name__ == '__main__':
    # Check for dependencies (assuming no changes needed within this function) 
    dependency_check()

    from w3af.core.ui.api.main import main
    sys.exit(main())
