#!/usr/bin/env python3
"""
sha1hash.py

Copyright 2006 Andres Riancho

This file is part of w3af, w3af.sourceforge.net .

w3af is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation version 2 of the License.

w3af is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with w3af; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
"""

import hashlib
import argparse


def usage():
    print('w3af - sha1 hash calculator')
    print('')
    print('Options:')
    print('  -h, --help     Print this help message.')
    print('  -e, --encode   String to be hashed.')
    print('')
    print('Example: sha1hash -e makeHash')


def main():
    parser = argparse.ArgumentParser(description='w3af - sha1 hash calculator')
    parser.add_argument('-e', '--encode', required=True, help='String to be hashed')
    args = parser.parse_args()

    encoded_bytes = args.encode.encode()  # Encode input as bytes
    sha1_hash = hashlib.sha1(encoded_bytes).hexdigest()
    print(sha1_hash)


if __name__ == "__main__":
    main()
