#!/usr/bin/env python3
"""
urlencode.py

Copyright 2024 Andres Riancho

This file is part of w3af, w3af.sourceforge.net .

w3af is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation version 2 of the License.

w3af is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with w3af; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
"""

import urllib.parse
import argparse


def usage():
    print('w3af - urlencoder')
    print('')
    print('Options:')
    print('  -h, --help     Print this help message.')
    print('  -s, --safe     Characters that should not be encoded, default is / .')
    print('  -e, --encode   String to be encoded.')
    print('')
    print('Example: urlencode -s &% -e encodeMeNow')


def main():
    parser = argparse.ArgumentParser(description='w3af - urlencoder')
    parser.add_argument('-s', '--safe', default='/.', help='Characters that should not be encoded')
    parser.add_argument('-e', '--encode', required=True, help='String to be encoded')
    args = parser.parse_args()

    encoded_string = urllib.parse.quote_plus(args.encode, safe=args.safe)
    print(encoded_string)


if __name__ == "__main__":
    main()
